npmScopes:
  curtischang:
    npmRegistryServer : "https://gitlab.dcedx.com/api/v4/projects/408/packages/npm/"
    npmPublishRegistry: "https://gitlab.dcedx.com/api/v4/projects/408/packages/npm/"

npmRegistries:
  //gitlab.dcedx.com/api/v4/projects/408/packages/npm/:
    npmAlwaysAuth: true
    npmAuthToken: "Z7wYokEenxFeJivJup6M"
